name: alarm_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.2
  cupertino_icons: ^1.0.8
  timezone: ^0.9.0
  vibration: ^1.8.4
  intl: ^0.18.0
  haptic_feedback: ^0.5.1+1
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/alarm_sound.mp3 # Add this line to include your audio file
